//
// Licensed Materials - Property of IBM
// 5724I83
// (C) Copyright IBM Corp. 1995, 2008 All Rights Reserved.
//
// ***** DO NOT EDIT THIS FILE *****

var lat = new Array(0);
var lng = new Array(0);
var markerwindowinfo = new Array(0);
var markerevent = new Array(0);
var markerlabel = new Array(0);
var markertype = new Array(0);
var firstshown = new Array(0);
var marker = new Array(0);

function hpbmaponload() {
	var map = new YahooMapsCtrl(document.getElementById("HPBMAP_20090508140144"), '36.370642, 140.464826', 4, YMapMode.MAP, YDatumType.TOKYO97);
	map.setVisibleSliderbar(true);
	map.setVisibleCentermark(true);
	map.setVisibleCentermarkButton(false);
	return map;
}